routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminLoginController;
use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\Admin\IndexController;
use App\Http\Controllers\Admin\SupportController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function (){
    Route::get('login', [AdminLoginController::class, 'showLoginForm'])->name('login-form');
    Route::post('login', [AdminLoginController::class, 'login'])->name('login-handler');
    Route::post('logout', [AdminLoginController::class, 'logout'])->name('logout');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth:admin']], function (){
    Route::get('/test', [TestController::class, 'index']);
    Route::get('/', [IndexController::class, 'index'])->name('index');
    Route::group(['prefix' => 'supports', 'as' => 'supports.'], function (){
        Route::get('/', [SupportController::class, 'index'])->name('index');
        Route::get('/{support}', [SupportController::class, 'show'])->name('show');
        Route::get('/change-status/{support}', [SupportController::class, 'changeStatus'])->name('change-status');
        Route::delete('/{support}', [SupportController::class, 'delete'])->name('delete');
    });
    Route::group(['prefix' => 'users', 'as' => 'users.'], function (){
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/{user}', [UserController::class, 'edit'])->name('edit');
        Route::put('/{user}', [UserController::class, 'update'])->name('update');
        Route::delete('/{user}', [UserController::class, 'delete'])->name('delete');
    });
    Route::group(['prefix' => 'complaints', 'as' => 'complaints.'], function (){
        Route::get('/', [ComplaintController::class, 'index'])->name('index');
        Route::get('/change-status/{complaint}', [ComplaintController::class, 'changeStatus'])->name('change-status');
        Route::delete('/{complaint}', [ComplaintController::class, 'delete'])->name('delete');
    });
});

routes/web.php
<?php

use App\Http\Controllers\Admin\AdminLoginController;
use App\Http\Controllers\Admin\IndexController;
use App\Http\Controllers\Admin\SupportController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\FrontPageController::class, 'index'])->name('home');
Route::get('/', [\App\Http\Controllers\FrontPageController::class, 'index'])->name('login');
Route::inertia('/about', 'About');
Route::inertia('/polityka_konfidentsiynosti', 'TermsOfService');

Route::post('/sendCode', [\App\Http\Controllers\ClientController::class, 'sendCode']);
Route::post('/checkCode', [\App\Http\Controllers\ClientController::class, 'checkCode'])->name('check-code');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    // Route::get('/dashboard', [\App\Http\Controllers\ClientController::class, 'index'])->name('dashboard');
//    Route::post('/makeRequest', [\App\Http\Controllers\ClientController::class, 'makeRequest']);
    Route::get('/profile', [\App\Http\Controllers\ClientController::class, 'index'])->name('dashboard');
    Route::get('/logout', [\App\Http\Controllers\ClientController::class, 'destroy']);
    Route::get('/delete', [\App\Http\Controllers\Api\SupportController::class, 'destroy']);
    Route::post('/edit-user', [\App\Http\Controllers\ClientController::class, 'update']);
    Route::post('/deleteRequest', [\App\Http\Controllers\ClientController::class, 'deleteRequest']);
    Route::post('/offRequest', [\App\Http\Controllers\ClientController::class, 'offRequest']);
    Route::post('/editRequest', [\App\Http\Controllers\ClientController::class, 'editRequest']);
});

Route::post('/step-first', [\App\Http\Controllers\ClientController::class, 'stepFirst']);
Route::post('/step-second', [\App\Http\Controllers\ClientController::class, 'stepSecond']);
Route::post('/step-third', [\App\Http\Controllers\ClientController::class, 'stepThird']);
Route::post('/step-fourth', [\App\Http\Controllers\ClientController::class, 'stepFourth']);
Route::post('/makeRequest', [\App\Http\Controllers\ClientController::class, 'makeRequest']);
Route::post('/makeDonate', [\App\Http\Controllers\ClientController::class, 'makeDonate']);
Route::get('/requests', [\App\Http\Controllers\CatalogController::class, 'byAll'])->name('requests');
Route::get('/{city:slug}', [\App\Http\Controllers\CatalogController::class, 'byCity'])->name('city');
Route::get('/d/{category:slug}', [\App\Http\Controllers\CatalogController::class, 'byCategory'])->name('category');
Route::get('/{city:slug}/{category_slug}', [\App\Http\Controllers\CatalogController::class, 'byCityCategory'])->name('category-with-city');

Route::get('/feedback', [\App\Http\Controllers\FeedbackController::class, 'index']);
Route::post('/feedback', [\App\Http\Controllers\FeedbackController::class, 'store']);

Route::post('/complaint', [\App\Http\Controllers\ComplaintController::class, 'store']);

Route::post('/password/update/custom', [\App\Http\Controllers\Auth\NewPasswordController::class, 'store']);
Route::post('forgot-password', [PasswordResetLinkController::class, 'store'])->name('password.email');

Route::get('/register', function(){
    return Redirect::to('/', 301);
});
Route::get('/login', function(){
    return Redirect::to('/', 301);
});

app/Models/Support.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Support
 *
 * @property int $id
 * @property int $status_id
 * @property int $city_id
 * @property int $category_id
 * @property int|null $assist_user_id
 * @property int|null $needy_user_id
 * @property bool $status
 * @property string $title
 * @property string $description
 * @property string $degree
 * @property bool $delivery
 * @property string|null $delivery_type
 * @property string|null $delivery_address
 * @property bool $is_other_needy
 * @property string|null $name
 * @property string|null $lastname
 * @property string|null $telegram
 * @property string|null $viber
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|Support newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Support newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Support query()
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereAssistUserId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereCategoryId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereCityId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereDegree($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereDelivery($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereDeliveryAddress($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereDeliveryType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereIsOtherNeedy($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereLastname($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereNeedyUserId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereStatusId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereTelegram($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Support whereViber($value)
 * @mixin \Eloquent
 */
class Support extends Model
{
    use HasFactory;

    protected $fillable = [
        'needy_user_id',
        'status_id',
        'city_id',
        'category_id',
        'status',
        'title',
        'description',
        'degree',
        'delivery',
        'delivery_type',
        'delivery_address',
        'is_other_needy',
        'name',
        'lastname',
        'phone',
        'telegram',
        'viber',
        'email'
    ];

    protected $with = [
        'relation_category',
        'relation_city',
        'user'
    ];

    protected $dates = [
        'created_at'
    ];
    // protected $dateFormat = 'd.m.Y';
    public static function findOrFail($id)
    {
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'needy_user_id');
    }

    public function supportStatus()
    {
        return $this->belongsTo(SupportStatus::class, 'status_id');
    }

    public function relation_category(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(SupportCategory::class, 'category_id');
    }

    public function relation_city(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(City::class, 'city_id');
    }

    public function changeStatus($status)
    {
        $this->update([
            'status' => $status
        ]);
    }

    public function deleteObj()
    {
        $this->delete();
    }
}

app/Http/Controllers/Admin/SupportController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\Admin\SupportAPHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ChangeStatusSupportRequest;
use App\Models\Support;
use Illuminate\Http\Request;

class SupportController extends Controller
{
    public $helper;

    public function __construct(SupportAPHelper $helper)
    {
        $this->helper = $helper;
    }

    public function index()
    {
        try {
            $vars = $this->helper->getIndexVars();
        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }

        return view('admin.supports.index', $vars);
    }

    public function show(Support $support)
    {
        try {
            $vars = $this->helper->getShowVars($support);
        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }

        return view('admin.supports.show', $vars);
    }

    public function delete(Support $support)
    {
        try {
            $support->deleteObj();
        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }

        return redirect()->back()->with('success', 'Success deleted!');
    }

    public function changeStatus(Support $support, ChangeStatusSupportRequest $request)
    {
        try {
            $support->changeStatus($request->status);
        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }

        return redirect()->back()->with('success', 'Success updated!');
    }
}

app/Http/Controllers/Api/SupportController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\StoreSupportRequest;
use App\Http\Requests\Api\UpdateSupportRequest;
use App\Http\Resources\Api\SupportCollection;
use App\Http\Resources\Api\SupportResource;
use App\Models\Support;
use function response;

class SupportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return SupportCollection
     */
    public function index()
    {
        return new SupportCollection(Support::paginate());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Api\StoreSupportRequest  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(StoreSupportRequest $request)
    {
        return response()->json(Support::create($request->all()));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Support  $support
     * @return \App\Http\Resources\Api\SupportResource
     */
    public function show(Support $support)
    {
        return new SupportResource($support);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Api\UpdateSupportRequest  $request
     * @param  \App\Models\Support  $support
     * @return \App\Http\Resources\Api\SupportResource
     */
    public function update(UpdateSupportRequest $request, Support $support)
    {
        return new SupportResource($support->update($request->all()));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Support  $support
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Support $support)
    {

        return response()->json($support->delete());
    }
}

resources/views/admin/supports/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Supports</h1>
                    <p>Закрытых запросов: {{ $listing->count() }}</p>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route("admin.index") }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Supports</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table id="example2" class="table table-bordered table-hover dataTable dtr-inline" aria-describedby="example2_info">
                                            <thead>
                                            <tr>
                                                <th>id</th>
                                                <th>title</th>
                                                <th>description</th>
                                                <th>city</th>
                                                <th>category</th>
                                                <th>user</th>
                                                <th>user phone</th>
                                                <th>status</th>
                                                <th>Критичність</th>
                                                <th>created_at</th>
                                                <th>
                                                    Action
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($items as $item)
                                                    <tr class="@if($loop->iteration % 2 == 0)odd @else even @endif">
                                                        <td>{{ $item->id }}</td>
                                                        <td>{{ $item->title }}</td>
                                                        <td>{{ mb_substr($item->description, 0, 100) }}</td>
                                                        <td>{{ $item->relation_city->name }}</td>
                                                        <td>{{ $item->relation_category->title }}</td>
                                                        <td>
                                                            @if($item->user)
                                                                <a href="{{ route('admin.users.edit', ['user' => $item->user]) }}">{{ $item->user->name }}</a>
                                                            @endif
                                                        </td>
                                                        <td>{{ $item->user->phone }}</td>
                                                        <td>
{{--                                                            {{ $item->supportStatus->title }}--}}
                                                            @if($item->status === true)
                                                                Включен
                                                            @elseif($item->status === false)
                                                                Отключен
                                                            @endif
                                                        </td>
                                                        <td>
                                                            @if($item->degree == 'grateful')
                                                                Буду вдячний
                                                            @elseif($item->degree == 'wait')
                                                                Терміново, але готовий зачекати
                                                            @elseif($item->degree == 'urgently')
                                                                Терміново потрібно
                                                            @endif
                                                        </td>
                                                        <td>{{ date_time_from_db($item->created_at) }}</td>
                                                        <td class="project-actions">
                                                            <a class="btn btn-info btn-sm" href="{{ route('admin.supports.show', ['support' => $item]) }}">
                                                                show
                                                            </a>
                                                            @if($item->status === true)
                                                                <a class="btn btn-success btn-sm" href="{{ route('admin.supports.change-status', ['support' => $item, 'status' => false]) }}">
                                                                    Выключить
                                                                </a>
                                                            @elseif($item->status === false)
                                                                <a class="btn btn-info btn-sm" href="{{ route('admin.supports.change-status', ['support' => $item, 'status' => true]) }}">
                                                                    Включить
                                                                </a>
                                                            @endif
                                                            <form class="d-inline-block" method="POST" action="{{ route('admin.supports.delete', ['support' => $item]) }}">
                                                                @csrf
                                                                @method("DELETE")
                                                                <button class="btn btn-danger btn-sm" type="submit">
                                                                    delete
                                                                </button>
                                                            </form>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                        {{ $items->links() }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/supports/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Supports</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route("admin.index") }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route("admin.supports.index") }}">Supports</a></li>
                        <li class="breadcrumb-item active">Support - {{ $support->id }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label>Ім’я та прізвище</label>
                                        <input value="{{ $support->user->name }}" type="text" class="form-control" disabled>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label>Телефон</label>
                                        <input value="{{ $support->user->phone }}" type="text" class="form-control" disabled>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input value="{{ $support->user->email }}" type="text" class="form-control" disabled>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label>Заголовок</label>
                                        <input value="{{ $support->title }}" type="text" class="form-control" disabled>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label>Опис</label>
                                        <input value="{{ $support->description }}" type="text" class="form-control" disabled>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label>Місто <div class="quote"><div class="quote__text">Окрім тимчасово окупованих територій</div></div></label>
                                        <input value="{{ $support->relation_city->name }}" type="text" class="form-control" disabled>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label>Категорію</label>
                                        <input value="{{ $support->relation_category->title }}" type="text" class="form-control" disabled>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label>Критичність</label>
                                        @if($support->degree == 'grateful')
                                            <input value="Буду вдячний" type="text" class="form-control" disabled>
                                        @elseif($support->degree == 'wait')
                                            <input value="Терміново, але готовий зачекати" type="text" class="form-control" disabled>
                                        @elseif($support->degree == 'urgently')
                                            <input value="Терміново потрібно" type="text" class="form-control" disabled>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label>Телеграм</label>
                                        <input value="{{ $support->telegram }}" type="text" class="form-control" disabled>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label>Вайбер</label>
                                        <input value="{{ $support->viber }}" type="text" class="form-control" disabled>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label>Вайбер відповідає номеру</label>
                                        @if($support->viber == $support->user->phone)
                                            <input value="Yes" type="text" class="form-control" disabled>
                                        @else
                                            <input value="No" type="text" class="form-control" disabled>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            @if($support->delivery)
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label>Доставка</label>
                                            <input value="Потрібно доставити" type="text" class="form-control" disabled>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group">
                                            <label>Служба доставки</label>
                                            @if($support->delivery_type == 'np')
                                                <input value="Нова пошта" type="text" class="form-control" disabled>
                                            @elseif($support->delivery_type == 'up')
                                                <input value="Укр. пошта" type="text" class="form-control" disabled>
                                            @elseif($support->delivery_type == 'other')
                                                <input value="Інше" type="text" class="form-control" disabled>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group">
                                            @if($support->delivery_address == 'np')
                                                <label>Місто та відділення вашої пошти</label>
                                                <input value="{{ $support->delivery_address }}" type="text" class="form-control" disabled>
                                            @elseif($support->delivery_type == 'up')
                                                <label>Місто та відділення вашої пошти</label>
                                                <input value="{{ $support->delivery_address }}" type="text" class="form-control" disabled>
                                            @elseif($support->delivery_type == 'other')
                                                <label>Бажаний спосіб доставки</label>
                                                <input value="{{ $support->delivery_address }}" type="text" class="form-control" disabled>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            @else
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label>Доставка</label>
                                            <input value="Є можливість забрати" type="text" class="form-control" disabled>
                                        </div>
                                    </div>
                                </div>
                            @endif

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection