routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminLoginController;
use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\Admin\IndexController;
use App\Http\Controllers\Admin\SupportController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function (){
    Route::get('login', [AdminLoginController::class, 'showLoginForm'])->name('login-form');
    Route::post('login', [AdminLoginController::class, 'login'])->name('login-handler');
    Route::post('logout', [AdminLoginController::class, 'logout'])->name('logout');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth:admin']], function (){
    Route::get('/test', [TestController::class, 'index']);
    Route::get('/', [IndexController::class, 'index'])->name('index');
    Route::group(['prefix' => 'supports', 'as' => 'supports.'], function (){
        Route::get('/', [SupportController::class, 'index'])->name('index');
        Route::get('/{support}', [SupportController::class, 'show'])->name('show');
        Route::get('/change-status/{support}', [SupportController::class, 'changeStatus'])->name('change-status');
        Route::delete('/{support}', [SupportController::class, 'delete'])->name('delete');
    });
    Route::group(['prefix' => 'users', 'as' => 'users.'], function (){
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/{user}', [UserController::class, 'edit'])->name('edit');
        Route::put('/{user}', [UserController::class, 'update'])->name('update');
        Route::delete('/{user}', [UserController::class, 'delete'])->name('delete');
    });
    Route::group(['prefix' => 'complaints', 'as' => 'complaints.'], function (){
        Route::get('/', [ComplaintController::class, 'index'])->name('index');
        Route::get('/change-status/{complaint}', [ComplaintController::class, 'changeStatus'])->name('change-status');
        Route::delete('/{complaint}', [ComplaintController::class, 'delete'])->name('delete');
    });
});

routes/web.php
<?php

use App\Http\Controllers\Admin\AdminLoginController;
use App\Http\Controllers\Admin\IndexController;
use App\Http\Controllers\Admin\SupportController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\FrontPageController::class, 'index'])->name('home');
Route::get('/', [\App\Http\Controllers\FrontPageController::class, 'index'])->name('login');
Route::inertia('/about', 'About');
Route::inertia('/polityka_konfidentsiynosti', 'TermsOfService');

Route::post('/sendCode', [\App\Http\Controllers\ClientController::class, 'sendCode']);
Route::post('/checkCode', [\App\Http\Controllers\ClientController::class, 'checkCode'])->name('check-code');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    // Route::get('/dashboard', [\App\Http\Controllers\ClientController::class, 'index'])->name('dashboard');
//    Route::post('/makeRequest', [\App\Http\Controllers\ClientController::class, 'makeRequest']);
    Route::get('/profile', [\App\Http\Controllers\ClientController::class, 'index'])->name('dashboard');
    Route::get('/logout', [\App\Http\Controllers\ClientController::class, 'destroy']);
    Route::get('/delete', [\App\Http\Controllers\Api\SupportController::class, 'destroy']);
    Route::post('/edit-user', [\App\Http\Controllers\ClientController::class, 'update']);
    Route::post('/deleteRequest', [\App\Http\Controllers\ClientController::class, 'deleteRequest']);
    Route::post('/offRequest', [\App\Http\Controllers\ClientController::class, 'offRequest']);
    Route::post('/editRequest', [\App\Http\Controllers\ClientController::class, 'editRequest']);
});

Route::post('/step-first', [\App\Http\Controllers\ClientController::class, 'stepFirst']);
Route::post('/step-second', [\App\Http\Controllers\ClientController::class, 'stepSecond']);
Route::post('/step-third', [\App\Http\Controllers\ClientController::class, 'stepThird']);
Route::post('/step-fourth', [\App\Http\Controllers\ClientController::class, 'stepFourth']);
Route::post('/makeRequest', [\App\Http\Controllers\ClientController::class, 'makeRequest']);
Route::post('/makeDonate', [\App\Http\Controllers\ClientController::class, 'makeDonate']);
Route::get('/requests', [\App\Http\Controllers\CatalogController::class, 'byAll'])->name('requests');
Route::get('/{city:slug}', [\App\Http\Controllers\CatalogController::class, 'byCity'])->name('city');
Route::get('/d/{category:slug}', [\App\Http\Controllers\CatalogController::class, 'byCategory'])->name('category');
Route::get('/{city:slug}/{category_slug}', [\App\Http\Controllers\CatalogController::class, 'byCityCategory'])->name('category-with-city');

Route::get('/feedback', [\App\Http\Controllers\FeedbackController::class, 'index']);
Route::post('/feedback', [\App\Http\Controllers\FeedbackController::class, 'store']);

Route::post('/complaint', [\App\Http\Controllers\ComplaintController::class, 'store']);

Route::post('/password/update/custom', [\App\Http\Controllers\Auth\NewPasswordController::class, 'store']);
Route::post('forgot-password', [PasswordResetLinkController::class, 'store'])->name('password.email');

Route::get('/register', function(){
    return Redirect::to('/', 301);
});
Route::get('/login', function(){
    return Redirect::to('/', 301);
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/css/lte/fontawesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/css/lte/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini">

@if(session('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif
@if(session('error'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ session('error') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif
<div class="wrapper">

    @include('admin.layouts.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
    @yield('content')
        <!-- /.content -->

        <a id="back-to-top" href="#" class="btn btn-primary back-to-top" role="button" aria-label="Scroll to top">
            <i class="fas fa-chevron-up"></i>
        </a>
    </div>
    <!-- /.content-wrapper -->

    <footer class="main-footer"></footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="/js/lte/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/js/lte/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/js/lte/adminlte.min.js"></script>

</body>
</html>

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../index3.html" class="brand-link">
        <img src="/images/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">AdminPanel</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">




        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{{ route('admin.index') }}" class="nav-link @if(request()->is('admin')) active @endif">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.users.index') }}" class="nav-link @if(request()->is('admin/users*')) active @endif">
                        <i class="nav-icon fas fa-user"></i>
                        <p>Users</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.supports.index') }}" class="nav-link @if(request()->is('admin/supports*')) active @endif">
                        <i class="nav-icon fas fa-th"></i>
                        <p>Supports</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.complaints.index') }}" class="nav-link @if(request()->is('admin/complaints*')) active @endif">
                        <i class="nav-icon fas fa-exclamation-triangle"></i>
                        <p>Complaints</p>
                    </a>
                </li>
                <li class="nav-item">
                    <form action="{{ route("admin.logout") }}" method="POST">
                        @csrf
                        <button type="submit" class="nav-link @if(request()->is('admin/supports*')) active @endif">
                            <p>Logout</p>
                        </button>
                    </form>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>
<script>
    import Button from "@/Components/Button";
    export default {
        components: {Button}
    }
</script>