routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminLoginController;
use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\Admin\IndexController;
use App\Http\Controllers\Admin\SupportController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function (){
    Route::get('login', [AdminLoginController::class, 'showLoginForm'])->name('login-form');
    Route::post('login', [AdminLoginController::class, 'login'])->name('login-handler');
    Route::post('logout', [AdminLoginController::class, 'logout'])->name('logout');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth:admin']], function (){
    Route::get('/test', [TestController::class, 'index']);
    Route::get('/', [IndexController::class, 'index'])->name('index');
    Route::group(['prefix' => 'supports', 'as' => 'supports.'], function (){
        Route::get('/', [SupportController::class, 'index'])->name('index');
        Route::get('/{support}', [SupportController::class, 'show'])->name('show');
        Route::get('/change-status/{support}', [SupportController::class, 'changeStatus'])->name('change-status');
        Route::delete('/{support}', [SupportController::class, 'delete'])->name('delete');
    });
    Route::group(['prefix' => 'users', 'as' => 'users.'], function (){
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/{user}', [UserController::class, 'edit'])->name('edit');
        Route::put('/{user}', [UserController::class, 'update'])->name('update');
        Route::delete('/{user}', [UserController::class, 'delete'])->name('delete');
    });
    Route::group(['prefix' => 'complaints', 'as' => 'complaints.'], function (){
        Route::get('/', [ComplaintController::class, 'index'])->name('index');
        Route::get('/change-status/{complaint}', [ComplaintController::class, 'changeStatus'])->name('change-status');
        Route::delete('/{complaint}', [ComplaintController::class, 'delete'])->name('delete');
    });
});

routes/web.php
<?php

use App\Http\Controllers\Admin\AdminLoginController;
use App\Http\Controllers\Admin\IndexController;
use App\Http\Controllers\Admin\SupportController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\FrontPageController::class, 'index'])->name('home');
Route::get('/', [\App\Http\Controllers\FrontPageController::class, 'index'])->name('login');
Route::inertia('/about', 'About');
Route::inertia('/polityka_konfidentsiynosti', 'TermsOfService');

Route::post('/sendCode', [\App\Http\Controllers\ClientController::class, 'sendCode']);
Route::post('/checkCode', [\App\Http\Controllers\ClientController::class, 'checkCode'])->name('check-code');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    // Route::get('/dashboard', [\App\Http\Controllers\ClientController::class, 'index'])->name('dashboard');
//    Route::post('/makeRequest', [\App\Http\Controllers\ClientController::class, 'makeRequest']);
    Route::get('/profile', [\App\Http\Controllers\ClientController::class, 'index'])->name('dashboard');
    Route::get('/logout', [\App\Http\Controllers\ClientController::class, 'destroy']);
    Route::get('/delete', [\App\Http\Controllers\Api\SupportController::class, 'destroy']);
    Route::post('/edit-user', [\App\Http\Controllers\ClientController::class, 'update']);
    Route::post('/deleteRequest', [\App\Http\Controllers\ClientController::class, 'deleteRequest']);
    Route::post('/offRequest', [\App\Http\Controllers\ClientController::class, 'offRequest']);
    Route::post('/editRequest', [\App\Http\Controllers\ClientController::class, 'editRequest']);
});

Route::post('/step-first', [\App\Http\Controllers\ClientController::class, 'stepFirst']);
Route::post('/step-second', [\App\Http\Controllers\ClientController::class, 'stepSecond']);
Route::post('/step-third', [\App\Http\Controllers\ClientController::class, 'stepThird']);
Route::post('/step-fourth', [\App\Http\Controllers\ClientController::class, 'stepFourth']);
Route::post('/makeRequest', [\App\Http\Controllers\ClientController::class, 'makeRequest']);
Route::post('/makeDonate', [\App\Http\Controllers\ClientController::class, 'makeDonate']);
Route::get('/requests', [\App\Http\Controllers\CatalogController::class, 'byAll'])->name('requests');
Route::get('/{city:slug}', [\App\Http\Controllers\CatalogController::class, 'byCity'])->name('city');
Route::get('/d/{category:slug}', [\App\Http\Controllers\CatalogController::class, 'byCategory'])->name('category');
Route::get('/{city:slug}/{category_slug}', [\App\Http\Controllers\CatalogController::class, 'byCityCategory'])->name('category-with-city');

Route::get('/feedback', [\App\Http\Controllers\FeedbackController::class, 'index']);
Route::post('/feedback', [\App\Http\Controllers\FeedbackController::class, 'store']);

Route::post('/complaint', [\App\Http\Controllers\ComplaintController::class, 'store']);

Route::post('/password/update/custom', [\App\Http\Controllers\Auth\NewPasswordController::class, 'store']);
Route::post('forgot-password', [PasswordResetLinkController::class, 'store'])->name('password.email');

Route::get('/register', function(){
    return Redirect::to('/', 301);
});
Route::get('/login', function(){
    return Redirect::to('/', 301);
});

app/Models/User.php
<?php

namespace App\Models;

use App\Mail\Auth\ResetPasswordEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Mail;

/**
 * App\Models\User
 *
 * @property int $id
 * @property string $name
 * @property string $lastname
 * @property string $email
 * @property string $phone
 * @property string|null $telegram
 * @property string|null $viber
 * @property \Illuminate\Support\Carbon|null $email_verified_at
 * @property \Illuminate\Support\Carbon|null $phone_verified_at
 * @property string $password
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string|null $two_factor_secret
 * @property string|null $two_factor_recovery_codes
 * @property string|null $two_factor_confirmed_at
 * @property int|null $city_id
 * @property-read string $profile_photo_url
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read int|null $notifications_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\Laravel\Sanctum\PersonalAccessToken[] $tokens
 * @property-read int|null $tokens_count
 * @method static \Database\Factories\UserFactory factory(...$parameters)
 * @method static \Illuminate\Database\Eloquent\Builder|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User query()
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCityId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereLastname($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePhone($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePhoneVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereTelegram($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereTwoFactorConfirmedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereTwoFactorRecoveryCodes($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereTwoFactorSecret($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereViber($value)
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'lastname',
        'email',
        'phone',
        'telegram',
        'viber',
        'password',
        'city_id'
    ];

    protected $with = [
        'relation_city'
    ];

    public function sendPasswordResetNotification($token)
    {
        Mail::to($this->email)->send(new ResetPasswordEmail($token, $this->email));
    }

    public function relation_city(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(City::class, 'city_id');
    }

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'phone_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function updateObj($data)
    {
        $this->update([
            'name' => $data->name,
            'lastname' => $data->lastname,
            'phone' => $data->phone,
            'email' => $data->email,
            'telegram' => $data->telegram,
            'viber' => $data->viber
        ]);
    }

    public function deleteObj()
    {
        Support::where('needy_user_id', $this->id)->delete();

        $this->delete();
    }

    public function setEmailAttribute($value)
    {
        $this->attributes['email'] = strtolower($value);
    }

    public function getEmailAttribute($value)
    {
        return strtolower($value);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\Admin\UserAPHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\UpdateUserRequest;
use App\Models\User;

class UserController extends Controller
{
    public $helper;

    public function __construct(UserAPHelper $helper)
    {
        $this->helper = $helper;
    }

    public function index()
    {
        try {
            $vars = $this->helper->getIndexVars();
        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }

        return view('admin.users.index', $vars);
    }

    public function edit(User $user)
    {
        try {
            $vars = $this->helper->getEditVars($user);
        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }

        return view('admin.users.edit', $vars);
    }

    public function update(User $user, UpdateUserRequest $request)
    {
        try {
            $user->updateObj($request);
        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }

        return redirect()->back()->with('success', 'Success updated!');
    }

    public function delete(User $user)
    {
        try {
            $user->deleteObj();
        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }

        return redirect()->back()->with('success', 'Success deleted!');
    }
}

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>User</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route("admin.index") }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route("admin.users.index") }}">Users</a></li>
                        <li class="breadcrumb-item active">User - {{ $user->id }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route('admin.users.update', ['user' => $user]) }}" method="POST" class="row">
                                @csrf
                                @method('PUT')
                                <div class="col">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $user->name) }}">
                                        @error('name')
                                        <small class="text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="lastname">Lastname</label>
                                        <input type="text" class="form-control" id="lastname" name="lastname" value="{{ old('lastname', $user->lastname) }}">
                                        @error('lastname')
                                        <small class="text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="phone">Phone</label>
                                        <input type="text" class="form-control" id="phone" name="phone" value="{{ old('phone', $user->phone) }}">
                                        @error('phone')
                                        <small class="text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="phone">Email</label>
                                        <input type="text" class="form-control" id="email" name="email" value="{{ old('email', $user->email) }}">
                                        @error('email')
                                        <small class="text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label for="telegram">Telegram</label>
                                        <input type="text" class="form-control" id="telegram" name="telegram" value="{{ old('telegram', $user->telegram) }}">
                                        @error('telegram')
                                        <small class="text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="viber">Viber</label>
                                        <input type="text" class="form-control" id="viber" name="viber" value="{{ old('viber', $user->viber) }}">
                                        @error('viber')
                                        <small class="text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                    <div class="form-group text-right">
                                        <button class="btn btn-success">Update</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Users</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route("admin.index") }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Users</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table id="example2" class="table table-bordered table-hover dataTable dtr-inline" aria-describedby="example2_info">
                                            <thead>
                                            <tr>
                                                <th>id</th>
                                                <th>name</th>
                                                <th>phone</th>
                                                <th>email</th>
                                                <th>city</th>
                                                <th>created_at</th>
                                                <th>
                                                    Action
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($items as $item)
                                                <tr class="@if($loop->iteration % 2 == 0)odd @else even @endif">
                                                    <td>{{ $item->id }}</td>
                                                    <td>{{ $item->name }}</td>
                                                    <td>{{ $item->phone }}</td>
                                                    <td>{{ $item->email }}</td>
                                                    <td>{{ $item->relation_city ? $item->relation_city->name : 'no set' }}</td>
                                                    <td>{{ date_time_from_db($item->created_at) }}</td>
                                                    <td class="project-actions">
                                                        <a class="btn btn-info btn-sm" href="{{ route('admin.users.edit', ['user' => $item]) }}">
                                                            show
                                                        </a>
                                                        <form class="d-inline-block" method="POST" action="{{ route('admin.users.delete', ['user' => $item]) }}">
                                                            @csrf
                                                            @method("DELETE")
                                                            <button class="btn btn-danger btn-sm" type="submit">
                                                                delete
                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                        {{ $items->links() }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection