routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminLoginController;
use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\Admin\IndexController;
use App\Http\Controllers\Admin\SupportController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function (){
    Route::get('login', [AdminLoginController::class, 'showLoginForm'])->name('login-form');
    Route::post('login', [AdminLoginController::class, 'login'])->name('login-handler');
    Route::post('logout', [AdminLoginController::class, 'logout'])->name('logout');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth:admin']], function (){
    Route::get('/test', [TestController::class, 'index']);
    Route::get('/', [IndexController::class, 'index'])->name('index');
    Route::group(['prefix' => 'supports', 'as' => 'supports.'], function (){
        Route::get('/', [SupportController::class, 'index'])->name('index');
        Route::get('/{support}', [SupportController::class, 'show'])->name('show');
        Route::get('/change-status/{support}', [SupportController::class, 'changeStatus'])->name('change-status');
        Route::delete('/{support}', [SupportController::class, 'delete'])->name('delete');
    });
    Route::group(['prefix' => 'users', 'as' => 'users.'], function (){
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/{user}', [UserController::class, 'edit'])->name('edit');
        Route::put('/{user}', [UserController::class, 'update'])->name('update');
        Route::delete('/{user}', [UserController::class, 'delete'])->name('delete');
    });
    Route::group(['prefix' => 'complaints', 'as' => 'complaints.'], function (){
        Route::get('/', [ComplaintController::class, 'index'])->name('index');
        Route::get('/change-status/{complaint}', [ComplaintController::class, 'changeStatus'])->name('change-status');
        Route::delete('/{complaint}', [ComplaintController::class, 'delete'])->name('delete');
    });
});

routes/web.php
<?php

use App\Http\Controllers\Admin\AdminLoginController;
use App\Http\Controllers\Admin\IndexController;
use App\Http\Controllers\Admin\SupportController;
use App\Http\Controllers\Admin\TestController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\FrontPageController::class, 'index'])->name('home');
Route::get('/', [\App\Http\Controllers\FrontPageController::class, 'index'])->name('login');
Route::inertia('/about', 'About');
Route::inertia('/polityka_konfidentsiynosti', 'TermsOfService');

Route::post('/sendCode', [\App\Http\Controllers\ClientController::class, 'sendCode']);
Route::post('/checkCode', [\App\Http\Controllers\ClientController::class, 'checkCode'])->name('check-code');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    // Route::get('/dashboard', [\App\Http\Controllers\ClientController::class, 'index'])->name('dashboard');
//    Route::post('/makeRequest', [\App\Http\Controllers\ClientController::class, 'makeRequest']);
    Route::get('/profile', [\App\Http\Controllers\ClientController::class, 'index'])->name('dashboard');
    Route::get('/logout', [\App\Http\Controllers\ClientController::class, 'destroy']);
    Route::get('/delete', [\App\Http\Controllers\Api\SupportController::class, 'destroy']);
    Route::post('/edit-user', [\App\Http\Controllers\ClientController::class, 'update']);
    Route::post('/deleteRequest', [\App\Http\Controllers\ClientController::class, 'deleteRequest']);
    Route::post('/offRequest', [\App\Http\Controllers\ClientController::class, 'offRequest']);
    Route::post('/editRequest', [\App\Http\Controllers\ClientController::class, 'editRequest']);
});

Route::post('/step-first', [\App\Http\Controllers\ClientController::class, 'stepFirst']);
Route::post('/step-second', [\App\Http\Controllers\ClientController::class, 'stepSecond']);
Route::post('/step-third', [\App\Http\Controllers\ClientController::class, 'stepThird']);
Route::post('/step-fourth', [\App\Http\Controllers\ClientController::class, 'stepFourth']);
Route::post('/makeRequest', [\App\Http\Controllers\ClientController::class, 'makeRequest']);
Route::post('/makeDonate', [\App\Http\Controllers\ClientController::class, 'makeDonate']);
Route::get('/requests', [\App\Http\Controllers\CatalogController::class, 'byAll'])->name('requests');
Route::get('/{city:slug}', [\App\Http\Controllers\CatalogController::class, 'byCity'])->name('city');
Route::get('/d/{category:slug}', [\App\Http\Controllers\CatalogController::class, 'byCategory'])->name('category');
Route::get('/{city:slug}/{category_slug}', [\App\Http\Controllers\CatalogController::class, 'byCityCategory'])->name('category-with-city');

Route::get('/feedback', [\App\Http\Controllers\FeedbackController::class, 'index']);
Route::post('/feedback', [\App\Http\Controllers\FeedbackController::class, 'store']);

Route::post('/complaint', [\App\Http\Controllers\ComplaintController::class, 'store']);

Route::post('/password/update/custom', [\App\Http\Controllers\Auth\NewPasswordController::class, 'store']);
Route::post('forgot-password', [PasswordResetLinkController::class, 'store'])->name('password.email');

Route::get('/register', function(){
    return Redirect::to('/', 301);
});
Route::get('/login', function(){
    return Redirect::to('/', 301);
});

app/Models/Complaint.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property $status
 * @property $support_id
 * @property $text
 */
class Complaint extends Model
{
    protected $table = 'complaints';
    protected $guarded = [];

    const STATUS_OPEN = "O";
    const STATUS_CLOSE = "C";

    public function support()
    {
        return $this->belongsTo(Support::class, 'support_id');
    }

    public static function createObj($support_id, $text)
    {
        $obj = self::create([
            'support_id' => $support_id,
            'text' => $text
        ]);

        return $obj;
    }

    public function changeStatus($status)
    {
        $this->update([
            'status' => $status
        ]);
    }

    public function deleteObj()
    {
        $this->delete();
    }
}

app/Http/Controllers/Admin/ComplaintController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\Admin\ComplaintAPHelper;
use App\Helpers\Admin\UserAPHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ChangeStatusComplaintRequest;
use App\Http\Requests\Admin\UpdateUserRequest;
use App\Models\Complaint;
use App\Models\User;

class ComplaintController extends Controller
{
    public $helper;

    public function __construct(ComplaintAPHelper $helper)
    {
        $this->helper = $helper;
    }

    public function index()
    {
        try {
            $vars = $this->helper->getIndexVars();
        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }

        return view('admin.complaints.index', $vars);
    }

    public function changeStatus(Complaint $complaint, ChangeStatusComplaintRequest $request)
    {
        try {
            $complaint->changeStatus($request->status);
        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }

        return redirect()->back()->with('success', 'Success updated!');
    }

    public function delete(Complaint $complaint)
    {
        try {
            $complaint->deleteObj();
        } catch (\DomainException $e) {
            return redirect()->back()->with('error', $e->getMessage());
        }

        return redirect()->back()->with('success', 'Success deleted!');
    }
}

app/Http/Controllers/ComplaintController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Auth\ComplaintRequest;
use App\Models\Complaint;

class ComplaintController extends Controller
{
    public function store(ComplaintRequest $request)
    {
        try {
            Complaint::createObj($request->support_id, $request->text);
        } catch (\DomainException $e) {
            return back();
        }

        return back();
    }
}

resources/views/admin/complaints/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Complaints</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route("admin.index") }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Complaints</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table id="example2" class="table table-bordered table-hover dataTable dtr-inline" aria-describedby="example2_info">
                                            <thead>
                                            <tr>
                                                <th>id</th>
                                                <th>text</th>
                                                <th>support</th>
                                                <th>support id</th>
                                                <th>status</th>
                                                <th>created_at</th>
                                                <th>
                                                    action
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($items as $item)
                                                <tr class="@if($loop->iteration % 2 == 0)odd @else even @endif">
                                                    <td>{{ $item->id }}</td>
                                                    <td>{{ $item->text }}</td>
                                                    <td>
                                                        @if($item->support)
                                                            <a href="{{ route('admin.supports.show', ['support' => $item->support]) }}">{{ $item->support->title }}</a>
                                                        @else
                                                            no set
                                                        @endif
                                                    </td>
                                                    <td>{{ $item->support_id }}</td>
                                                    <td>
                                                        @if($item->status == $complaint_status_open)
                                                            open status
                                                        @elseif($item->status == $complaint_status_close)
                                                            close status
                                                        @endif
                                                    </td>
                                                    <td>{{ date_time_from_db($item->created_at) }}</td>
                                                    <td class="project-actions">
                                                        @if($item->status == $complaint_status_open)
                                                            <a class="btn btn-success btn-sm" href="{{ route('admin.complaints.change-status', ['complaint' => $item, 'status' => $complaint_status_close]) }}">
                                                                set close status
                                                            </a>
                                                        @elseif($item->status == $complaint_status_close)
                                                            <a class="btn btn-info btn-sm" href="{{ route('admin.complaints.change-status', ['complaint' => $item, 'status' => $complaint_status_open]) }}">
                                                                set open status
                                                            </a>
                                                        @endif
                                                        <form class="d-inline-block" method="POST" action="{{ route('admin.complaints.delete', ['complaint' => $item]) }}">
                                                            @csrf
                                                            @method("DELETE")
                                                            <button class="btn btn-danger btn-sm" type="submit">
                                                                delete
                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                        {{ $items->links() }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection